CREATE TABLE IF NOT EXISTS job_descriptions (
  jd_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_code        VARCHAR(50) UNIQUE NOT NULL,
  title           TEXT NOT NULL,
  department      TEXT,
  family_id       INTEGER REFERENCES job_families(family_id),
  level           VARCHAR(20),
  employment_type VARCHAR(20),
  location        TEXT,
  content_md      TEXT NOT NULL,
  version         INTEGER NOT NULL DEFAULT 1,
  created_by      VARCHAR(50),
  created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMP
  ,source_name     VARCHAR(30)
  ,source_url      TEXT
  ,source_external_id VARCHAR(255)
  ,source_company  TEXT
  ,source_published_at TIMESTAMP
  ,source_fetched_at TIMESTAMP
  ,source_hash     VARCHAR(64)
);

CREATE INDEX IF NOT EXISTS idx_job_desc_family ON job_descriptions(family_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_job_desc_source
  ON job_descriptions(source_name, source_external_id)
  WHERE source_name IS NOT NULL AND source_external_id IS NOT NULL;
