CREATE TABLE IF NOT EXISTS jd_taxonomy_tags (
  tag_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag_name      TEXT UNIQUE NOT NULL,
  description   TEXT,
  parent_tag_id INTEGER REFERENCES jd_taxonomy_tags(tag_id)
);
