CREATE TABLE IF NOT EXISTS jd_versions (
  version_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jd_id          INTEGER NOT NULL REFERENCES job_descriptions(jd_id) ON UPDATE CASCADE ON DELETE CASCADE,
  version_number INTEGER NOT NULL,
  content_md     TEXT NOT NULL,
  edited_by      VARCHAR(50) NOT NULL,
  edited_at      TIMESTAMP NOT NULL DEFAULT NOW(),
  change_summary TEXT,
  CONSTRAINT jd_versions_jd_id_version_number_key UNIQUE (jd_id, version_number)
);

CREATE INDEX IF NOT EXISTS idx_jd_versions_jd_id ON jd_versions(jd_id);