CREATE TABLE IF NOT EXISTS candidate_profiles (
  candidate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name    TEXT NOT NULL,
  email        TEXT UNIQUE NOT NULL,
  phone        TEXT,
  resume_text  TEXT NOT NULL,
  created_at   TIMESTAMP NOT NULL DEFAULT NOW()
);